### PR TITLE
bug fixing in DedicatedReceiveAsync

### PR DESCRIPTION
**Pull request by ligu**
Finally I've found the bug responsible for the endless disconnection/reconnection issues with SSL, this is the fix for it.
The problem was, that in case of SSL, the first 8 bytes read from the stream usually comes in 2 reads, and in those cases the old logic falsely assigned the msg correlationId value, so the response could not be matched with the prevailing request sent.
I've also did some optimization, by removing the separated header array, because I havent seen any specific function of it.
Unfortunately I could not rerun the related unit-tests, the testrunner is somehow broke since yesterday in my VS setup, so hopefully I haven't broke anything else in the code.

### CODE REVIEW

**Comment by ligu** [comment]
After some testing in a near-production system, it seems that the reading of the body of a message has the same kind of problem. I will try to fix that tomorrow.

**Comment by awr** [comment]
Good find.
I'll try and take a look through tonight, but may not get to it until Monday.

Looks like the build is failing on the tests though. Not sure why you can't run locally, but you should be able to see the status through the CI links.

**Comment by awr** [comment]
I like the move to ArraySegment, but not sure on the root cause on the correlation id -- the read function *should* continue until 8 bytes are read. Is it because the socket is recreated by a new Send while the receive is in progress?

You're right though -- there seems to be little value in the header array.

**Comment by ligu** [comment]
Look at this log fragment:

`
2017-02-06 10:43:04.290Z|98|11|Successful SSL connection to localhost, SslProtocol:Tls, KeyExchange:DiffieHellman.1024, Cipher:Aes128.128, Hash:Sha1.160, Authenticated:True, MutuallyAuthenticated:False, Encrypted:True, Signed:True|Write|[]|C:\Work\git\SB.KafkaNet\src\KafkaClient\Connections\SslTransport.cs|101||END#
2017-02-06 10:43:04.290Z|99|11|Reading (8? bytes) from localhost:6668|Write|[]|C:\Work\git\SB.KafkaNet\src\KafkaClient\Connections\SslTransport.cs|174||END#
2017-02-06 10:43:04.291Z|100|15|Sending Produce SportsbookFixture (id 2, 419 bytes) to localhost:6668|Write|[]|C:\Work\git\SB.KafkaNet\src\KafkaClient\Connections\Connection.cs|94||END#
2017-02-06 10:43:04.291Z|101|15|Produce -----> localhost:6668 {Context:{id:2,version:2,client:KC},
Request:{Api:Produce,RequiredAcks:1,Timeout:00:00:05,Topics:[{TopicName:SportsbookFixture,PartitionId:1,Codec:None,Messages:1}]}}|Write|[]|C:\Work\git\SB.KafkaNet\src\KafkaClient\Connections\Connection.cs|95||END#
2017-02-06 10:43:04.291Z|102|15|Writing 419? bytes (id 2) to localhost:6668|Write|[]|C:\Work\git\SB.KafkaNet\src\KafkaClient\Connections\SslTransport.cs|208||END#
2017-02-06 10:43:04.292Z|103|14|Wrote 419 bytes (id 2) to localhost:6668|Write|[]|C:\Work\git\SB.KafkaNet\src\KafkaClient\Connections\SslTransport.cs|212||END#
2017-02-06 10:43:04.337Z|104|10|Read 4 bytes from localhost:6668|Write|[]|C:\Work\git\SB.KafkaNet\src\KafkaClient\Connections\SslTransport.cs|179||END#
2017-02-06 10:43:04.337Z|105|10|Reading (4? bytes) from localhost:6668|Write|[]|C:\Work\git\SB.KafkaNet\src\KafkaClient\Connections\SslTransport.cs|174||END#
2017-02-06 10:43:04.337Z|106|11|Read 1 bytes from localhost:6668|Write|[]|C:\Work\git\SB.KafkaNet\src\KafkaClient\Connections\SslTransport.cs|179||END#
2017-02-06 10:43:04.337Z|107|11|Reading (3? bytes) from localhost:6668|Write|[]|C:\Work\git\SB.KafkaNet\src\KafkaClient\Connections\SslTransport.cs|174||END#
2017-02-06 10:43:04.337Z|108|25|Read 3 bytes from localhost:6668|Write|[]|C:\Work\git\SB.KafkaNet\src\KafkaClient\Connections\SslTransport.cs|179||END#
2017-02-06 10:43:04.337Z|109|25|Matched Produce response (id 2, 49? bytes) from localhost:6668|Write|[]|C:\Work\git\SB.KafkaNet\src\KafkaClient\Connections\Connection.cs|212||END#
2017-02-06 10:43:04.337Z|110|25|Reading (45? bytes) from localhost:6668|Write|[]|C:\Work\git\SB.KafkaNet\src\KafkaClient\Connections\SslTransport.cs|174||END#
2017-02-06 10:43:04.337Z|111|25|Read 45 bytes from localhost:6668|Write|[]|C:\Work\git\SB.KafkaNet\src\KafkaClient\Connections\SslTransport.cs|179||END#
2017-02-06 10:43:04.337Z|112|25|Received Produce response (id 2, 49 bytes)|Write|[]|C:\Work\git\SB.KafkaNet\src\KafkaClient\Connections\Connection.cs|333||END#
`

That beginning 8 bytes are read in chunks of 4,1,3. I guess it's because after the bytes are received from the server side, the SSL codec has to decrypt them, and maybe the decryptor put's its results into the output stream in chunks.

Actually the root cause was in this code fragment:
`                            await _transport.ReadBytesAsync(buffer, KafkaEncoder.ResponseHeaderSize, bytesRead => {
                                for (var i = 0; i < bytesRead; i++) {
                                    header[headerOffset++] = buffer[i];
                                }
                            }, CancellationToken.None).ConfigureAwait(false);
`
bytesRead func was executed after each chunk of read, but was always reading from the beginning of the internal buffer (buffer[i] instead of something like buffer[offset+i]).

**Comment by ligu** [comment]
Regarding to the unit tests, the problem is on my dev PC, it's not the problem of this project.
I've installed the .net Core Addon, and since then the test runner component is not working in my Visual Studio. I'll fix it sooner or later somehow.

**Pull request merged**
